export const MOCK_TOWNS = [
  {
    "id": "penaguila",
    "type": "town",
    "author": "Gent de Penàguila",
    "title": "Penàguila",
    "comarca": "L'Alcoià",
    "content": "Penàguila és un municipi del País Valencià a la comarca de l'Alcoià. El seu terme té 49,9 km².",
    "population": "320 hab",
    "linkTo": "Gent de Penàguila",
    "image": true,
    "image_url": "/assets/towns/penaguila/1.jpg",
    "avatar_url": "/assets/towns/penaguila/2.jpg",
    "lat": 38.6315,
    "lng": -0.3892,
    "created_at": "2026-08-10T08:47:00.000Z"
  },
  {
    "id": "benifallim",
    "type": "town",
    "author": "Gent de Benifallim",
    "title": "Benifallim",
    "comarca": "L'Alcoià",
    "content": "Benifallim és una població del País Valencià a la comarca de l'Alcoià.",
    "population": "110 hab",
    "linkTo": "Gent de Benifallim",
    "image": true,
    "image_url": "/assets/towns/benifallim/1.jpg",
    "avatar_url": "/assets/towns/benifallim/2.jpg",
    "lat": 38.6439,
    "lng": -0.4632,
    "created_at": "2026-08-04T14:15:00.000Z"
  },
  {
    "id": "la-torre-de-les-macanes",
    "type": "town",
    "author": "Gent de La Torre",
    "title": "La Torre de les Maçanes",
    "comarca": "L'Alacantí",
    "content": "La Torre de les Maçanes és una vila i municipi del País Valencià situat a la comarca de l'Alacantí, a la comarca històrica de la Foia de Xixona.",
    "population": "700 hab",
    "linkTo": "Gent de La Torre",
    "image": true,
    "image_url": "/assets/towns/la-torre-de-les-macanes/1.jpg",
    "avatar_url": "/assets/towns/la-torre-de-les-macanes/2.jpg",
    "lat": 38.5919,
    "lng": -0.4184,
    "created_at": "2026-08-20T00:01:00.000Z"
  },
  {
    "id": "sella",
    "type": "town",
    "author": "Gent de Sella",
    "title": "Sella",
    "comarca": "Marina Baixa",
    "content": "Sella és un municipi de la comarca de la Marina Baixa, al País Valencià.",
    "population": "570 hab",
    "linkTo": "Gent de Sella",
    "image_url": "/assets/towns/sella/1.jpg",
    "avatar_url": "/assets/towns/sella/2.jpg",
    "lat": 38.6083,
    "lng": -0.2721,
    "created_at": "2026-08-11T08:00:00.000Z"
  },
  {
    "id": "orxeta",
    "type": "town",
    "author": "Gent d'Orxeta",
    "title": "Orxeta",
    "comarca": "Marina Baixa",
    "content": "Orxeta és un municipi de la comarca de la Marina Baixa, al País Valencià. Amb 812 habitants segons l'INE del 2022.",
    "population": "820 hab",
    "linkTo": "Gent d'Orxeta",
    "image_url": "/assets/towns/orxeta/1.jpg",
    "avatar_url": "/assets/towns/orxeta/2.jpg",
    "lat": 38.5630,
    "lng": -0.2618,
    "created_at": "2026-08-12T08:00:00.000Z"
  },
  {
    "id": "relleu",
    "type": "town",
    "author": "Gent de Relleu",
    "title": "Relleu",
    "comarca": "Marina Baixa",
    "content": "Relleu és un municipi de la comarca de la Marina Baixa, situat al bell mig d'una vall envoltada de muntanyes.",
    "population": "1200 hab",
    "linkTo": "Gent de Relleu",
    "image_url": "/assets/towns/relleu/1.jpg",
    "avatar_url": "/assets/towns/relleu/2.jpg",
    "lat": 38.5878,
    "lng": -0.3114,
    "created_at": "2026-08-13T08:00:00.000Z"
  },
  {
    "id": "alcoleja",
    "type": "town",
    "author": "Gent d'Alcoleja",
    "title": "Alcoleja",
    "comarca": "El Comtat",
    "content": "Alcoleja és un municipi de la comarca del Comtat, al País Valencià, situat a la falda de la serra d'Aitana.",
    "population": "170 hab",
    "linkTo": "Gent d'Alcoleja",
    "image_url": "/assets/towns/alcoleja/1.jpg",
    "avatar_url": "/assets/towns/alcoleja/2.jpg",
    "lat": 38.6811,
    "lng": -0.3314,
    "created_at": "2026-08-14T08:00:00.000Z"
  },
  {
    "id": "xixona",
    "type": "town",
    "author": "Gent de Xixona",
    "title": "Xixona",
    "comarca": "L'Alacantí",
    "content": "Xixona és un municipi de País Valencià, pertanyent a la comarca de l'Alacantí i també capital de la històrica comarca de la Foia de Xixona. És mundialment coneguda per ser el bressol del torró. El 2023, tenia 7.032 habitants, segons l'INE.",
    "population": "6800 hab",
    "linkTo": "Gent de Xixona",
    "image_url": "/assets/towns/xixona/1.jpg",
    "avatar_url": "/assets/towns/xixona/2.jpg",
    "lat": 38.5398,
    "lng": -0.5085,
    "created_at": "2026-08-15T08:00:00.000Z"
  },
  {
    "id": "tibi",
    "type": "town",
    "author": "Gent de Tibi",
    "title": "Tibi",
    "comarca": "L'Alcoià",
    "content": "Tibi és un municipi del País Valencià, a la comarca de l'Alcoià, conegut pel seu històric pantà.",
    "population": "1700 hab",
    "linkTo": "Gent de Tibi",
    "image_url": "/assets/towns/tibi/1.jpg",
    "avatar_url": "/assets/towns/tibi/2.jpg",
    "lat": 38.5306,
    "lng": -0.5761,
    "created_at": "2026-08-16T08:00:00.000Z"
  }
];
